### PR TITLE
Group similar utilities together

### PR DESCRIPTION
**Pull request by cpeel**
This is a fantastic list and this graybeard is excited to update his toolchain.

I noticed that there were several tools that were similar but not grouped together -- this PR attempts to make that better. The only tool that got moved between sections was `atuin` to group it with the shell-based tools, notably `fzf` which appear related.

### CODE REVIEW

**Review by mhoye — APPROVED** [review]
This is great, thank you.

**Comment by cpeel** [comment]
Working to re-rebase this after the updates in `upstream/main`.

**Comment by cpeel** [comment]
Done. Note there are 2 commits -- the first one de-dups shell additions that came in after the last merge.

Note that I changed the indented bullet formatting to a form that works for GitHub.

**Comment by mhoye** [comment]
Thank you for reworking this so it could be merged. I'm sorry for causing you the extra work, I didn't see the first one when it arrived.

**Comment by cpeel** [comment]
You bet - thanks again for putting this together!

**Pull request merged**
